blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/Fugushiva/jobnomad/blob/master/README.md
    about: Consulter le README et les docs avant d'ouvrir une issue.
